[mypy]
python_version = 3.9
# Exclude common folders from analysis
exclude = (?:\.venv|\.mypy_cache|\.git|\.pytest_cache)

[mypy-plotly.*]
ignore_missing_imports = True

[mypy-plotly.graph_objects.*]
ignore_missing_imports = True

[mypy-bokeh.*]
ignore_missing_imports = True

[mypy-urllib3.*]
ignore_missing_imports = True
